name: Publish
on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Clear npm cache
        run: |
          npm cache clean --force
          npm config set registry https://registry.npmjs.org/

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: |
          npm install --prefer-offline --no-audit --no-fund
          npm install --prefer-offline --no-audit --no-fund || npm install --prefer-offline --no-audit --no-fund

      - name: build frontend
        run: npm run build

      - name: install WiX
        run: |
          curl -L https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -o wix311-binaries.zip
          7z x wix311-binaries.zip -owix311
          echo "WIX=$env:GITHUB_WORKSPACE\wix311" >> $env:GITHUB_ENV

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}